"""Generate the ablation LaTeX table from meta.json, parallel to build_results_table.

Three discover-$k$ methods --- the full method and two ablations:

  * **Full (discover-$k$)**   --- ``agentic_clustering_discoverk``
  * **$-$ refinement loop**   --- ``agentic_clustering_synthonly_discoverk``
    (classify against the synthesizer's first taxonomy; no auditor/critic/investigator)
  * **$-$ task description**  --- ``agentic_clustering_notask_discoverk``
    (full loop end-to-end with empty ``config.instructions``)

Rows = datasets, column groups = the three methods $\\times$ {ARI, NMI, ACC}.
Reuses ``load_metrics`` / ``DATASETS`` / ``_fmt`` from build_results_table so
rounding, dataset order, and missing-cell rendering match the main table.
Missing cells render as ``--`` (e.g. an ablation run still in flight), so
re-running the builder fills them in as predictions land.

Run after new ablation predictions land:

    uv run --native-tls python -m benchmarking.data_processing.build_ablation_table

Writes to ``paper/ablation_table.tex``.
"""

from __future__ import annotations

from benchmarking.data_processing.build_results_table import (
    DATASETS,
    METRICS,
    MethodDisplay,
    _fmt,
    load_metrics,
)
from benchmarking.paths import ROOT

# Row order within each method group is fixed; column-group order left to right.
ABLATION_METHODS: list[MethodDisplay] = [
    MethodDisplay("agentic_clustering_discoverk",           "Full (discover-$k$)"),
    MethodDisplay("agentic_clustering_synthonly_discoverk", "$-$ refinement loop"),
    MethodDisplay("agentic_clustering_notask_discoverk",    "$-$ task description"),
]

_METRICS_PER_METHOD = len(METRICS)  # ARI, NMI, ACC


def build_table() -> str:
    n_methods = len(ABLATION_METHODS)
    col_spec = "l" + (" ccc" * n_methods)

    # Top header: each method spans its 3 metric columns.
    top_header = " & ".join(
        [""]
        + [f"\\multicolumn{{{_METRICS_PER_METHOD}}}{{c}}{{\\textbf{{{m.display}}}}}"
           for m in ABLATION_METHODS]
    ) + " \\\\"

    # One cmidrule under each method's 3-column block.
    cmid = "".join(
        f"\\cmidrule(lr){{{2 + i * _METRICS_PER_METHOD}-"
        f"{1 + (i + 1) * _METRICS_PER_METHOD}}}"
        for i in range(n_methods)
    )

    sub_header = " & ".join(
        ["\\textbf{Dataset}"] + ["ARI", "NMI", "ACC"] * n_methods
    ) + " \\\\"

    rows: list[str] = []
    for d in DATASETS:
        cells = [d.display]
        for m in ABLATION_METHODS:
            metrics = load_metrics(m.key, d.key)
            if metrics is None:
                cells.extend(["--"] * _METRICS_PER_METHOD)
            else:
                # is_best=False -> plain 2-decimal (no underlining in an ablation).
                cells.extend(_fmt(metrics[name], False) for name in METRICS)
        rows.append("    " + " & ".join(cells) + " \\\\")

    lines = [
        "% Auto-generated by benchmarking/data_processing/build_ablation_table.py.",
        "% Do not edit by hand --- re-run the builder after new ablation predictions land.",
        "\\begin{table*}[t]",
        "  \\centering",
        "  \\small",
        f"  \\begin{{tabular}}{{{col_spec}}}",
        "    \\toprule",
        f"    {top_header}",
        f"    {cmid}",
        f"    {sub_header}",
        "    \\midrule",
        *rows,
        "    \\bottomrule",
        "  \\end{tabular}",
        "  \\caption{Ablations on our method (discover-$k$).}",
        "  \\label{tab:ablations}",
        "\\end{table*}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    out_path = ROOT / "paper" / "ablation_table.tex"
    out_path.write_text(build_table(), encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
