"""Build design_ablations_table.tex from the two front-end sweeps.

The 6--7 proposer / 1.0x sample cell is the production discover-$k$ configuration
(SKILL.md says "start with 6-7 proposals", and --initial-proposers defaults to
whatever the skill says), so its column is read from the main seed=0 discover-$k$
runs rather than from a dedicated sweep cell. That is why the sweeps themselves
only carry the off-default variants: re-running the default inside the sweep
would duplicate production.

Dispatch counts are derived exactly as compare_proposer_sweep.py derives them --
proposals + audits + investigations + synthesizer outputs + critiques -- so the
baseline row is comparable with the sweep rows rather than computed a second way.

    uv run --native-tls python -m benchmarking.data_processing.build_design_ablations_table

Writes to `results/tables/` (or `--out-dir`).
"""

from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

from benchmarking.paths import table_out_dir

REPO = Path(__file__).resolve().parents[2]
PROPOSER = REPO / "results" / "proposer_sweep" / "comparison.json"
SAMPLE = REPO / "results" / "sample_size_sweep" / "comparison.json"
CLUSTERING = REPO / "results" / "clustering"
PRED = REPO / "results" / "predictions" / "agentic_clustering_discoverk"


def _count_glob(d: Path, pat: str) -> int:
    return len(list(d.glob(pat))) if d.is_dir() else 0


def sweep_row(path: Path, variant: str) -> tuple[int, float, float, int]:
    rows = [r for r in json.loads(path.read_text(encoding="utf-8"))
            if r.get("variant") == variant and r.get("k_actual") is not None]
    dk = sum(abs(r["k_actual"] - r["k_in_scope"]) for r in rows)
    inv = statistics.mean([r.get("n_investigations") or 0 for r in rows])
    dis = statistics.mean([r.get("total_dispatches") or 0 for r in rows])
    return dk, inv, dis, len(rows)


def production_row() -> tuple[int, float, float, int]:
    """The default cell: the main seed=0 discover-k runs."""
    golds = {r["dataset"]: r["k_in_scope"]
             for r in json.loads(PROPOSER.read_text(encoding="utf-8"))
             if r.get("k_in_scope") is not None}
    dks, invs, diss = [], [], []
    for ds, gold in golds.items():
        meta = PRED / ds / "seed=0.meta.json"
        ws = CLUSTERING / ds / "seed=0_discoverk"
        if not meta.exists() or not ws.is_dir():
            continue
        m = json.loads((ws / "state.json").read_text(encoding="utf-8"))["meta"]
        n_synth = (_count_glob(ws, "synthesis_*.json")
                   + _count_glob(ws / "archive", "synthesis_*.json")
                   - _count_glob(ws, "synthesis_*_clusters.json"))
        dks.append(abs(json.loads(meta.read_text(encoding="utf-8"))["k_actual"] - gold))
        invs.append(m.get("total_investigations") or 0)
        diss.append(sum([m.get("total_proposals") or 0,
                         m.get("total_audits") or 0,
                         m.get("total_investigations") or 0,
                         max(n_synth, 0),
                         m.get("total_critiques") or 0]))
    return sum(dks), statistics.mean(invs), statistics.mean(diss), len(dks)


def main() -> int:
    out_path = table_out_dir(__doc__) / "design_ablations_table.tex"
    base = production_row()
    rows = [
        ("\\textit{Proposer count}", None),
        ("2--3 proposers", sweep_row(PROPOSER, "v0")),
        ("4--5 proposers", sweep_row(PROPOSER, "v1")),
        ("\\textbf{6--7 proposers (default)}", base),
        ("8--9 proposers", sweep_row(PROPOSER, "v3")),
        ("\\textit{Sample size (per proposer)}", None),
        ("0.5$\\times$", sweep_row(SAMPLE, "v1")),
        ("\\textbf{1.0$\\times$ (default)}", base),
        ("2.0$\\times$", sweep_row(SAMPLE, "v2")),
    ]
    body = []
    for label, vals in rows:
        if vals is None:
            body.append("    \\midrule")
            body.append(f"    \\multicolumn{{4}}{{l}}{{{label}}} \\\\")
            body.append("    \\midrule")
            continue
        dk, inv, dis, n = vals
        bold = label.startswith("\\textbf")
        f = (lambda s: f"\\textbf{{{s}}}") if bold else (lambda s: s)
        body.append(f"    {label} & {f(str(dk))} & {f(f'{inv:.1f}')} & {dis:.1f} \\\\")
    ns = {v[3] for _, v in rows if v}
    n = sorted(ns)[0]

    tex = f"""% Auto-generated by benchmarking/data_processing/build_design_ablations_table.py.
% Do not edit by hand --- re-run the builder after new sweep results land.
\\begin{{table}}[t]
  \\centering
  \\small
  \\begin{{tabular}}{{l ccc}}
    \\toprule
    \\textbf{{Front-end setting}} & $\\Sigma|\\Delta k|$ & \\makecell{{mean\\\\investig.}} & \\makecell{{mean\\\\dispatch}} \\\\
{chr(10).join(body)}
    \\bottomrule
  \\end{{tabular}}
  \\caption{{Design ablations (discover-$k$, aggregated across all benchmark
  datasets). The upper panel varies the number of proposers dispatched in
  parallel before synthesis; the lower panel varies how many texts each proposer
  samples, as a multiple of the default. All other settings are held at their
  production values. $\\Sigma|\\Delta k|$ is the summed absolute deviation of the
  discovered cluster count from gold; lower is better. \\emph{{Investig.}} and
  \\emph{{dispatch}} are the mean per-dataset counts of investigation rounds and
  total agent dispatches.}}
  \\label{{tab:design-ablations}}
\\end{{table}}
"""
    out_path.write_text(tex, encoding="utf-8")
    print(f"wrote {out_path}")
    print(tex)
    return 0


if __name__ == "__main__":
    sys.exit(main())
