"""Build paper/seed_variance_table.tex from the multi-seed discover-k runs.

Sibling of build_results_table.py / build_ablation_table.py. Unlike those, which
report a single designated seed, this one reads every seed present for the
discover-k method and reports mean +/- sd across them.

CLINC150 and GoEmotions carry a gold "none" class, and on those the headline ARI
mixes two things: how well in-scope documents are clustered, and how many "none"
documents the loop routed into in-scope clusters. The second column pair
separates them by recomputing ARI over in-scope documents only, which is what
makes CLINC150's spread interpretable rather than mysterious.

    uv run --native-tls python -m benchmarking.data_processing.build_seed_table
"""

from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

from sklearn.metrics import adjusted_rand_score

REPO = Path(__file__).resolve().parents[2]
PRED = REPO / "results" / "predictions" / "agentic_clustering_discoverk"
OUT = REPO / "paper" / "seed_variance_table.tex"

# Display order and labels match results_table.tex / ablation_table.tex.
DATASETS = [
    ("banking77", "Banking77"),
    ("clinc150", "CLINC150"),
    ("massive_intent", "MASSIVE-Intent"),
    ("massive_domain", "MASSIVE-Domain"),
    ("goemotions", "GoEmotions"),
    ("twenty_newsgroups", "20 Newsgroups"),
    ("stackexchange", "StackExchange"),
]
HAS_NONE = {"clinc150", "goemotions"}


def seeds_for(ds: str) -> list[int]:
    return sorted(int(p.stem.split("=")[1].split(".")[0])
                  for p in PRED.glob(f"{ds}/seed=*.meta.json")
                  # exclude side-runs such as seed=0_tokrun / seed=999
                  if p.stem.split("=")[1].split(".")[0].isdigit()
                  and int(p.stem.split("=")[1].split(".")[0]) < 100)


def in_scope_ari(ds: str, seed: int) -> float | None:
    """ARI over documents whose gold label is not the none class."""
    p = PRED / ds / f"seed={seed}.jsonl"
    if not p.exists():
        return None
    rows = [json.loads(l) for l in p.read_text(encoding="utf-8").splitlines() if l.strip()]
    keep = [r for r in rows if not r.get("is_none")]
    if not keep or len(keep) == len(rows):
        return None
    return adjusted_rand_score([r["gold_label"] for r in keep],
                               [r["predicted_cluster_id"] for r in keep])


def fmt(vals: list[float]) -> str:
    if len(vals) == 1:
        return f"{vals[0]:.3f}"
    return f"{statistics.mean(vals):.3f} {{\\scriptsize $\\pm$ {statistics.stdev(vals):.3f}}}"


def main() -> int:
    rows, n_seeds = [], set()
    for ds, label in DATASETS:
        seeds = seeds_for(ds)
        if not seeds:
            continue
        n_seeds.add(len(seeds))
        metas = [json.loads((PRED / ds / f"seed={s}.meta.json").read_text(encoding="utf-8"))
                 for s in seeds]
        ks = [m["k_actual"] for m in metas]
        aris = [m["metrics"]["ari"] for m in metas]
        nmis = [m["metrics"]["nmi"] for m in metas]
        accs = [m["metrics"]["acc"] for m in metas]
        ins = [v for s in seeds if (v := in_scope_ari(ds, s)) is not None]
        kcell = (f"{statistics.mean(ks):.0f} {{\\scriptsize $\\pm$ {statistics.stdev(ks):.0f}}}"
                 if len(ks) > 1 else f"{ks[0]}")
        rows.append((label, kcell, fmt(aris), fmt(nmis), fmt(accs),
                     fmt(ins) if ins else "---"))

    n = sorted(n_seeds)[0] if len(n_seeds) == 1 else min(n_seeds)
    body = "\n".join(
        f"    {lab} & {k} & {a} & {nm} & {ac} & {ins} \\\\" for lab, k, a, nm, ac, ins in rows)
    tex = f"""% Auto-generated by benchmarking/data_processing/build_seed_table.py.
% Do not edit by hand --- re-run the builder after new seed predictions land.
\\begin{{table*}}[t]
  \\centering
  \\small
  \\begin{{tabular}}{{l c cccc}}
    \\toprule
    \\textbf{{Dataset}} & $k$ & ARI & NMI & ACC & ARI (in-scope) \\\\
    \\midrule
{body}
    \\bottomrule
  \\end{{tabular}}
  \\caption{{Mean $\\pm$ standard deviation over {n} seeds in the discover-$k$ setting.
  \\emph{{ARI (in-scope)}} recomputes ARI over documents whose gold label is not the
  ``none'' class, and is reported only for the two datasets that have one.}}
  \\label{{tab:seed-variance}}
\\end{{table*}}
"""
    OUT.write_text(tex, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(rows)} datasets, {n} seeds)")
    print(tex)
    return 0


if __name__ == "__main__":
    sys.exit(main())
