"""Generate the LaTeX dataset summary table from per-dataset meta.json files.

Run after `process_all`:

    uv run --native-tls python -m benchmarking.data_processing.build_summary_table

Writes to `paper/dataset_table.tex`. Per-dataset metadata that doesn't live in
meta.json (display label, type, prior-art source) is in `DISPLAY` below.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from benchmarking.paths import DATA_DERIVED, ROOT


@dataclass(frozen=True)
class DatasetDisplay:
    name: str
    display: str
    data: str
    type_: str


# Order here = row order in the table. `data` describes what kind of text the documents
# are (e.g. "Reddit comments"); `type_` is the clustering task type (intent / emotion /
# topic / domain). Full source handles, configs, and revisions live in the appendix.
DISPLAY: list[DatasetDisplay] = [
    DatasetDisplay("banking77", "Banking77", "banking queries", "intent"),
    DatasetDisplay("clinc150", "CLINC150", "assistant queries", "intent"),
    DatasetDisplay("massive_intent", "MASSIVE-Intent", "assistant queries", "intent"),
    DatasetDisplay("massive_domain", "MASSIVE-Domain", "assistant queries", "domain"),
    DatasetDisplay("goemotions", "GoEmotions", "Reddit comments", "emotion"),
    DatasetDisplay("twenty_newsgroups", "20 Newsgroups", "Usenet posts", "topic"),
    DatasetDisplay("stackexchange", "StackExchange", "forum titles", "topic (forum)"),
]


def _format_int(n: int) -> str:
    return f"{n:,}"


def _format_not_in_cluster(share_none: float) -> str:
    return f"{share_none * 100:.1f}\\%"


def build() -> str:
    rows: list[str] = []
    for d in DISPLAY:
        meta_path = DATA_DERIVED / d.name / "meta.json"
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        rows.append(
            " & ".join(
                [
                    d.display,
                    d.data,
                    d.type_,
                    _format_int(meta["n_docs"]),
                    str(meta["k_in_scope"]),
                    _format_not_in_cluster(meta["share_none"]),
                    f"{meta['mean_text_chars']:.0f}",
                ]
            )
            + " \\\\"
        )

    body = "\n    ".join(rows)
    return _TEMPLATE.format(body=body)


_TEMPLATE = r"""% Auto-generated by benchmarking/data_processing/build_summary_table.py.
% Do not edit by hand — re-run the builder after `process_all`.
\begin{{table*}}[t]
  \centering
  \small
  \begin{{tabular}}{{lllrrrr}}
    \toprule
    \textbf{{Dataset}} & \textbf{{Data type}} & \textbf{{Cluster type}} & $N$ & $k$ & \textbf{{Not in cluster}} & \textbf{{Mean chars}} \\
    \midrule
    {body}
    \bottomrule
  \end{{tabular}}
  \caption{{\textbf{{Benchmark datasets.}} \textbf{{Data type}} indicates what kind of text the documents are; \textbf{{Cluster type}} indicates the clustering task. $N$: total documents. $k$: number of in-scope gold classes. \textbf{{Not in cluster}} is the share of documents whose gold label falls outside the $k$ in-scope clusters --- non-zero only for CLINC150 (out-of-scope queries) and GoEmotions (neutral). Mean text length is in characters. Source handles, configs, splits, and the full processing recipe for each dataset are in Appendix~\ref{{sec:appendix-datasets}}.}}
  \label{{tab:datasets}}
\end{{table*}}
"""


def main() -> None:
    out_path = ROOT / "paper" / "dataset_table.tex"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(build(), encoding="utf-8")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
